## Import libraries

In [1]:
import pandas as pd
import numpy as np

## Load datasets

In [2]:
X_train_smote = pd.read_csv("../datasets/X_train_smote.csv")

X_test = pd.read_csv("../datasets/X_test.csv")

y_train_smote = pd.read_csv("../datasets/y_train_smote.csv")

y_test = pd.read_csv("../datasets/y_test.csv")

## Check shapes

In [3]:
print(X_train_smote.shape)

print(X_test.shape)

print(y_train_smote.shape)

print(y_test.shape)

(2948388, 61)
(370479, 61)
(2948388, 1)
(370479, 1)


In [4]:
# Converting DataFrames to Series

y_train_smote = y_train_smote.squeeze()
y_test = y_test.squeeze()

In [5]:
print(type(y_train_smote))

print(type(y_test))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


## Train First Machine Learning Model

## 1. Import model

In [6]:
from sklearn.linear_model import LogisticRegression

## 2. Train model

In [7]:
log_model = LogisticRegression(max_iter = 1000)

log_model.fit(X_train_smote, y_train_smote)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


## 3. Generate the predictions

In [8]:
y_pred_log = log_model.predict(X_test)

## 4. Check prediction sample

In [9]:
print(y_pred_log[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]


## Evaluate Logistic Regression Model

## 1. Import metrics

In [10]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

## 2. Accuracy

In [11]:
log_accuracy = accuracy_score(y_test, y_pred_log)

print("Accuracy: ", log_accuracy)

Accuracy:  0.9660547561400241


## 3. Precision

In [12]:
log_precision = precision_score(y_test, y_pred_log)

print("Precision: ", log_precision)

Precision:  0.10287973739182334


## 4. Recall 

In [13]:
log_recall = recall_score(y_test, y_pred_log)

print("Recall: ", log_recall)

Recall:  0.7145077720207254


## 5. F1 Score

In [14]:
log_f1 = f1_score(y_test, y_pred_log)

print("F1 Score: ", log_f1)

F1 Score:  0.1798617451415156


## 6. ROC-AUC Score

In [15]:
log_roc_auc = roc_auc_score(y_test, y_pred_log)

print("ROC-AUC Score: ", log_roc_auc)

ROC-AUC Score:  0.8409399087644605


## 7. Confusion Matrix

In [16]:
log_cm = confusion_matrix(y_test, y_pred_log)

print(log_cm)

[[356524  12025]
 [   551   1379]]


## 8. Classification Report

In [17]:
print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98    368549
           1       0.10      0.71      0.18      1930

    accuracy                           0.97    370479
   macro avg       0.55      0.84      0.58    370479
weighted avg       0.99      0.97      0.98    370479



## Decision Tree Classifier

## 1. Import library

In [18]:
from sklearn.tree import DecisionTreeClassifier

## 2. Initialize Decision Tree model

In [19]:
tree_model = DecisionTreeClassifier(
    random_state = 42
)

## 3. Train the model

In [20]:
tree_model.fit(
    X_train_smote,
    y_train_smote
)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


## 4. Make predictions

In [21]:
y_pred_tree = tree_model.predict(X_test)

## 5. Check prediction sample

In [22]:
print(y_pred_tree[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


## Decision Tree Evaluation

## 1. Accuracy

In [23]:
from sklearn.metrics import accuracy_score

tree_accuracy = accuracy_score(
    y_test,
    y_pred_tree
)

print("Accuracy:", tree_accuracy)

Accuracy: 0.9968338286380605


## 2. Precision

In [24]:
from sklearn.metrics import precision_score

tree_precision = precision_score(
    y_test,
    y_pred_tree
)

print("Precision:", tree_precision)

Precision: 0.656469615543613


## 3. Recall

In [25]:
from sklearn.metrics import recall_score

tree_recall = recall_score(
    y_test,
    y_pred_tree
)

print("Recall:", tree_recall)

Recall: 0.8227979274611399


## 4. F1 Score

In [26]:
from sklearn.metrics import f1_score

tree_f1 = f1_score(
    y_test,
    y_pred_tree
)

print("F1 Score:", tree_f1)

F1 Score: 0.7302828236376179


## 5. ROC-AUC Score

In [27]:
from sklearn.metrics import roc_auc_score

tree_roc_auc = roc_auc_score(
    y_test,
    y_pred_tree
)

print("ROC-AUC Score:", tree_roc_auc)

ROC-AUC Score: 0.9102715695441796


## 6. Confusion Matrix

In [28]:
from sklearn.metrics import confusion_matrix

tree_cm = confusion_matrix(
    y_test,
    y_pred_tree
)

print(tree_cm)

[[367718    831]
 [   342   1588]]


## 7. Classification Report

In [29]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred_tree
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    368549
           1       0.66      0.82      0.73      1930

    accuracy                           1.00    370479
   macro avg       0.83      0.91      0.86    370479
weighted avg       1.00      1.00      1.00    370479



## Random Forest Classifier

## 1. Import library

In [30]:
from sklearn.ensemble import RandomForestClassifier

## 2. Initialize Random Forest model

In [31]:
rf_model = RandomForestClassifier(
    n_estimators = 100,
    random_state = 42,
    n_jobs = -1
)

## 3. Train the model

In [32]:
rf_model.fit(
    X_train_smote,
    y_train_smote
)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


## 4. Make predictions

In [33]:
y_pred_rf = rf_model.predict(X_test)

## 5. Check prediction sample

In [34]:
print(y_pred_rf[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


## Random Forest Evaluation

## 1. Accuracy

In [35]:
from sklearn.metrics import accuracy_score

rf_accuracy = accuracy_score(
    y_test,
    y_pred_rf
)

print("Accuracy:", rf_accuracy)

Accuracy: 0.998210424882382


## 2. Precision

In [36]:
from sklearn.metrics import precision_score

rf_precision = precision_score(
    y_test,
    y_pred_rf
)

print("Precision:", rf_precision)

Precision: 0.8613804905875642


## 3. Recall

In [37]:
from sklearn.metrics import recall_score

rf_recall = recall_score(
    y_test,
    y_pred_rf
)

print("Recall:", rf_recall)

Recall: 0.7823834196891192


## 4. F1 Score

In [38]:
from sklearn.metrics import f1_score

rf_f1 = f1_score(
    y_test,
    y_pred_rf
)

print("F1 Score:", rf_f1)

F1 Score: 0.8199837089329352


## 5. ROC-AUC Score

In [39]:
from sklearn.metrics import roc_auc_score

rf_roc_auc = roc_auc_score(
    y_test,
    y_pred_rf
)

print("ROC-AUC Score:", rf_roc_auc)

ROC-AUC Score: 0.8908620386203805


## 6. Confusion Matrix

In [40]:
from sklearn.metrics import confusion_matrix

rf_cm = confusion_matrix(
    y_test,
    y_pred_rf
)

print(rf_cm)

[[368306    243]
 [   420   1510]]


## 7. Classification Report

In [41]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred_rf
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    368549
           1       0.86      0.78      0.82      1930

    accuracy                           1.00    370479
   macro avg       0.93      0.89      0.91    370479
weighted avg       1.00      1.00      1.00    370479

